name: flumip_server
description: Mipgen automation backend using Serverpod server.
version: 0.7.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  serverpod: 3.4.11
  uuid: ^4.6.0
  get_it: ^9.2.1
  mailer: ^6.4.1

dev_dependencies:
  lints: ^6.0.0
  test: '^1.24.2'
  serverpod_test: 3.4.11

