name: staging build pipeline

on:
  push:
    branches:
      - staging

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: |
          cd flumip_server && flutter pub get
          cd ../flumip_flutter && flutter pub get

      - name: Analyze code
        run: |
          cd flumip_server && flutter analyze
          cd ../flumip_flutter && flutter analyze

      - name: Build
        run: |
          cd flumip_server && dart compile exe bin/main.dart
          cd ../flumip_flutter && flutter build web --release

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint-and-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set Up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Get dependencies
        run: |
          cd flumip_server && dart pub get

      - name: Inject passwords.yaml
        run: |
          echo "${{ secrets.PASSWORDS_YAML }}" > flumip_server/config/passwords.yaml

      - name: Run tests
        run: |
          cd flumip_server && dart test --tags "unit && action"

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject passwords.yaml
        run: |
          echo "${{ secrets.PASSWORDS_YAML }}" > flumip_server/config/passwords.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd flumip_server
          docker build -f DEV.Dockerfile -t flumip:staging .

      - name: Save Docker image as tar
        run: |
          docker save flumip:staging -o flumip_staging.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          rm: true
          source: "flumip_staging.tar"
          target: "~/flumip_staging.tar"

      - name: Execute remote script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            #!/bin/bash
            docker stop flumip_staging || true
            docker rm flumip_staging || true
            docker image rm flumip:staging || true
            docker load -i ~/flumip_staging.tar/flumip_staging.tar
            docker stop postgres_staging || true
            docker rm postgres_staging || true
            docker network rm flumip_staging || true
            docker network create flumip_staging || true
            docker run -d --name postgres_staging -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_STAGING_KEY }} -e POSTGRES_DB=flumip_staging --network flumip_staging -p 8090:5432 postgres:latest
            docker run -d --name flumip_staging -e SERVERPOD_DATABASE_PASSWORD='${{ secrets.POSTGRES_STAGING_KEY }}' -e runmode=staging -e logging=verbose --network flumip_staging -p 8088:8080 flumip:staging